name: form_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OpenSans-SemiBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf